### ISSUE TITLE
xdebug not working - xdebug.so is missing

### ISSUE THREAD

**Issue by vmasciotta** [clean-docker/PHP-Apache#3]
Hi,
thank you for your great work!

I needed to enable xdebug, so after a `./xdebug` I thought that xdebug was correctly enabled but I couldn't connect to the docker machine.
After a little debug I found out that `/usr/local/lib/php/extensions/no-debug-non-zts-20121212/xdebug.so` was missing.

I don't know if it's just me but the only way I'm able to solve the problem is to add this `RUN pecl install xdebug-2.5.5 && pecl channel-update pecl.php.net && docker-php-ext-enable xdebug` to my local build based on your image. After that now xdebug.so is where is expected to be and works fine now.
Am I missing something about how to launch/install xdebug or is this a "bug"?

Thanks

**Comment by rafaelstz** [comment]
Thanks for the report, I did the fix here: https://github.com/clean-docker/Magento1/commit/8715211a8d82f1ac7bc21472e0fdad3c367261a5
