### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by niziou** [clean-docker/PHP-Apache#7]
I have a question and suggestion to update php version in the docker image. I was trying to get the latest build but stumbled upon errors with your docker image. Is there any reason behind using 5.5 instead of 5.6?

**Comment by rafaelstz** [comment]
✅  Done, it's now upgrade to use PHP 5.6!
https://github.com/clean-docker/Magento1/commit/958aa4cdba00cd4e434193db82f8071aae355c1c
